### ISSUE TITLE
:octocat:  Compléter profil GH

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-camel#1]
- [x] Ajouter un avatar 🙏 
- [x] Te créer une [page de profil](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/about-your-profile)

![image](https://user-images.githubusercontent.com/5235127/193950914-7e5c3f09-9741-45e9-8734-62358307e17a.png)

**Comment by AntoineArthurG** [comment]
Hello Adriens, all done pour moi :+1:

**Comment by adriens** [comment]
YES :heavy_heart_exclamation: C'est bien stylé :sunglasses: 
![image](https://user-images.githubusercontent.com/5235127/194830870-afc497fe-3868-4156-b78a-7c773598df5f.png)

**Comment by adriens** [comment]
Et en plus sur l'issue `#1` :muscle: 
![image](https://user-images.githubusercontent.com/5235127/194831059-7eff4f10-f0bf-424a-b5a9-024296422113.png)
