### ISSUE TITLE
:whale:  Puller les images Zookeeper Kafka Kowl

### ISSUE THREAD

**Issue by Kenneth-OPT** [opt-nc/opt-temps-attente-agences-camel#14]
Récupération des images docker via les commandes
docker run --name zookeeper -d --net host ubuntu/zookeeper:latest
docker run --name kafka -d --net host --name kafka ubuntu/kafka:latest

Les conteneurs se lancent
![image](https://user-images.githubusercontent.com/109996637/214705154-ea02fe67-e80b-4112-bf64-aa61bfbf447e.png)

Et semblent communiquer, cf. log conteneur kafka ci-dessous :
![image](https://user-images.githubusercontent.com/109996637/214705387-8238d9de-ff10-4d20-bb08-d9d827072083.png)

Récupération de l'image docker de kowl pour pouvoir afficher les topics kafka via la commande : 
docker run --name kowl -d --net host -e KAFKA_BROKERS=localhost:9092 quay.io/cloudhut/kowl:latest

Le conteneur s'exécute seulement si celui de temps-attente-agences-api est arrêté
![image](https://user-images.githubusercontent.com/109996637/214705795-89aac0b0-cb35-4916-92f6-9b226bca17fb.png)
Cela est lié au fait qu'il utilise le même port 8080, cf. log ci-dessous : 
![image](https://user-images.githubusercontent.com/109996637/214705988-89aa20d2-a6e5-46ca-a02a-827dddccca41.png)

A voir comment modifier ce port.

A noter que le moment, je ne parviens pas encore à accéder à la page kowl.

**Comment by adriens** [comment]
:warning: Ne plus utiliser `kowl`
:point_right: utiliser [opt-nc/atelier-spring-kafka/](https://github.com/opt-nc/atelier-spring-kafka/)

**Comment by Kenneth-OPT** [comment]
Thank you bien pour le lien.

**Comment by adriens** [comment]
> Thank you bien pour le lien.

:bulb: You're welcome, hésite pas à follower cette repo, elle est maintenue activement

**Comment by Kenneth-OPT** [comment]
Création du fichier docker-compose qui comporte le conteneur ci-dessous dans l'ordre de démarrage :

- opt-temps-attente-agences-api
- zookeeper 
- kafka
- kowl

Pour exécuter les conteneurs utiliser la commande 
```shell
docker-compose up
```

A noter qu'il faut ajouter dans le fichier hosts la ligne ci-dessous pour que Kafka puisse répondre
```shell
127.0.0.1        kafka
```

**Comment by adriens** [comment]
:point_right:  Yes, traditionnellment on met le fichier docker-compte à la racine du projet
