### ISSUE TITLE
Route Camel via XML d'une API Rest vers Docker Kafka

### ISSUE THREAD

**Issue by Kenneth-OPT** [opt-nc/opt-temps-attente-agences-camel#16]

**Comment by adriens** [comment]
Yes, tu m'as bien teasé tt à l'heure mon salaud :rofl: Hâte de voir tout ça les gars :heavy_heart_exclamation: 
Bon we sous la :sun_behind_rain_cloud:

**Comment by Kenneth-OPT** [comment]
cf #10 
Commande à exécuter pour lancer la route
```shell
camel run route-kafka.xml --dep camel.dependencies=org.apache.camel:camel-kafka
```
Le paramètre "--dep" permet d'importer la dépendance Kafka qui est utilisée dans la route.
Pour importer plusieurs dépendances, il faut utiliser le paramètre "--deps"

**Comment by Kenneth-OPT** [comment]
Affichage via Kowl du topics dans Kafka
![image](https://user-images.githubusercontent.com/109996637/218037833-dcf76ae0-8f33-4a43-bd43-ed71e52cd2ac.png)

**Comment by adriens** [comment]
Magnifique les gars, c'est magnifique :clap: 

:point_right: checkez un peu ça @mbarre  @spencer-forrest-opt :star_struck:

**Comment by Kenneth-OPT** [comment]
Les données provenant de l 'api sont directement envoyés avec succès vers un topic kafka créé manuellement.
