### ISSUE TITLE
Route Camel XML en mode Consumer Kafka

### ISSUE THREAD

**Issue by Kenneth-OPT** [opt-nc/opt-temps-attente-agences-camel#17]
Créer une route Camel qui  consomme les données de temps d'attente des agences envoyées dans Kafka par l'intermédiaire de la première route mise en place.

**Comment by Kenneth-OPT** [comment]
La commande pour exécuter la route depuis un terminal, ici Windows Terminal :
```bash
camel run route-kafka-json.xml --dep camel.dependencies=org.apache.camel:camel-kafka
```

A noter que  pour fonctionner la route doit spécifier comme précédemment le nom du topic Kafka et en plus un nom de groupid. Dans l'exemple il est simplement nommé "test"
![image](https://user-images.githubusercontent.com/109996637/222878213-38926100-054f-4c8d-8972-ddb828e8fdc9.png)

Ce groupid sera alors visible au niveau du Consumer Groups de Kowl
![image](https://user-images.githubusercontent.com/109996637/222878188-2b6bb62f-7ea1-4eb4-8b03-cfc7228241aa.png)

Le fichier de sorti sera automatiquement mis à jour à chaque fois que le producer alimentera Kafak.

**Comment by adriens** [comment]
Very good @Kenneth-OPT , bien penser à mettre à dispo ces commandes dans un `.md` qu ipermet de dérouler tout cela en pas à pas, avec des copier/coller de scripts sur un env vierge :pray:
