### ISSUE TITLE
Comment exécuter les 2 routes en une seule commande

### ISSUE THREAD

**Issue by Kenneth-OPT** [opt-nc/opt-temps-attente-agences-camel#18]
Pour ce faire, il suffit simplement d'indiquer les noms des fichiers xml contenant les routes comme suit
```bash
camel run route-kafka3.xml route-kafka-json.xml --dep camel.dependencies=org.apache.camel:camel-kafka > camel-output.log &
```
A noter que la commande ci-dessous permet d'envoyer l'ensemble des sorties écran dans un fichier log "camel-output.log" et exécute les routes en tâche de fond.

Pour afficher le job correspondant dans un Terminal Windows, exécuter les commandes ci-dessous : 
![image](https://user-images.githubusercontent.com/109996637/222878640-6cd886b4-6e6e-4da3-9e11-f6a2eb5a7d7d.png)

Ou celle-ci pour plus de détails : 
![image](https://user-images.githubusercontent.com/109996637/222878822-366a63e9-c3ee-4c51-9e14-e94870b5872b.png)

Arrêt de tous les jobs
```powershell
Get-Job | Stop-Job
```
Suppression de tous les jobs
```powershell
Get-Job | Remove-Job
```

**Comment by adriens** [comment]
:bulb:

**Comment by adriens** [comment]
Yo les gars, où est le .md que je puisse jouer avec tout ça ?

**Comment by Kenneth-OPT** [comment]
Yo, j'ai préféré commencer par faire du nettoyage dans les issues ouvertes pour gagner en lisibilité. :sweat_smile:
J'espère pouvoir finaliser ça dans la soirée, au plus tard demain... ça dépend si ma descendance me laisse le champ libre ce soir :dizzy_face:

**Comment by adriens** [comment]
Yep, je vois ça, c cool je vois le ménage opéré, 👍
