### ISSUE TITLE
:sponge: Rangement rapport et presentation

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-camel#23]
# :grey_question: Contexte

il me semble que j'avais poussé : 

- [PRESENTATION.pdf](https://github.com/opt-nc/opt-temps-attente-agences-camel/blob/main/PRESENTATION.pdf)
- [RAPPORT.pdf](https://github.com/opt-nc/opt-temps-attente-agences-camel/blob/main/RAPPORT.pdf)

sous `doc`

:point_up: Il faut que la racine du projet soir la plus clean possible : seule la "substantifique moêlle" doit apparaître lorsque l'on arrive sur la repo.

# :dart: Actions

- [x] Déplacer rapport sous doc
- [x] Déplacer PRESENTATION sous doc

**Comment by Kenneth-OPT** [comment]
Bizarre... C'est fait. :smile:

**Comment by adriens** [comment]
Yes, c good sur main désormais : 

![image](https://user-images.githubusercontent.com/5235127/230213684-da976e77-5306-4c20-96f5-5af18707a0d2.png)

**Comment by adriens** [comment]
@Kenneth-OPT , peux-tu stp veiller à flagger les sous-issues comme réalisées ?

![image](https://user-images.githubusercontent.com/5235127/230213784-4283f4d7-cfdd-4b29-ac6c-44ab61490190.png)
