### ISSUE TITLE
:camel:  Route Camel - Localhost 🛣️

### ISSUE THREAD

**Issue by Kenneth-OPT** [opt-nc/opt-temps-attente-agences-camel#24]
La syntaxe pour le paramétrage d'une route Kafka en XML se fait comme suit :
```xml 
 <to uri="kafka:temps-attente?brokers=localhost:9092&amp;key=idAgence"/>
```
Que ce soit avec _localhost_ ou _127.0.0.1_ Camel essai systématiquement de résoudre le nom _kafka:9092_ et l'erreur ci-dessous s'affiche si le fichier host du poste local n'est pas paramétré en conséquence :
![image](https://user-images.githubusercontent.com/109996637/231372161-17d2aac4-e41f-4d30-b420-03ee0122a03d.png)

Le nom du conteneur Kafka dans le yaml du docker-compose a même été modifié pour tester si ce nom n'était pas lié à cette tentative de résolution, sans résultat.

Un autre test qui reste à faire serait de mettre l'adresse IP locale du poste, mais GlobalProtect bloque ce flux. 

Ou encore paramétrer la route vers un Kafka d'un environnement de test, à condition que le flux sur le port 9092 soit autorisé par les admins réseaux.

**Comment by adriens** [comment]
Hello @Kenneth-OPT , merci pour le ticket. Je vais voir avec @mbarre  pour son expertise.
D'ici là, je vais modifier le `/etc/host`

**Comment by mbarre** [comment]
Hello @Kenneth-OPT , j'ai déjà eu ce problème, j'ai reussi à m'en débarrasser il n'y a pas si longtemps :sweat_smile: 
Je vais jeter un oeil à ton docker-compose

**Comment by mbarre** [comment]
Je ne trouve pas ton docker-compose, tu pourrais le pusher ou me dire où il est s'il est déjà sur github stp ?

**Comment by Kenneth-OPT** [comment]
> Hello @Kenneth-OPT , j'ai déjà eu ce problème, j'ai reussi à m'en débarrasser il n'y a pas si longtemps 😅 Je vais jeter un oeil à ton docker-compose

Hello @mbarre,

Ce serait donc bien lié à la configuration Docker :sweat:


 Voilà le fichier [docker-compose]( https://github.com/opt-nc/opt-temps-attente-agences-camel/blob/main/scripts/temps_attente.yml).

Merci d'avance.

**Comment by mbarre** [comment]
@Kenneth-OPT , je t'ai ajouté la conf qui avait resolu le pb de mon coté.
Je l'ai mis sur la branche https://github.com/opt-nc/opt-temps-attente-agences-camel/tree/fix/docker_compose

Essaie le docker-compose pour voir si ca regle ton pb avant de faire le merge.

**Comment by adriens** [comment]
> Je ne trouve pas ton docker-compose

Oui, il faut un réseau dédié. @Kenneth-OPT @AntoineArthurG , quand plsueiurs images collaborent, il faut passer par un docker-compose.

**Comment by Kenneth-OPT** [comment]
> > Je ne trouve pas ton docker-compose
> 
> Oui, il faut un réseau dédié. @Kenneth-OPT @AntoineArthurG , quand plsueiurs images collaborent, il faut passer par un docker-compose.

Yes, c'est bien ce qui est utilisé 
![image](https://user-images.githubusercontent.com/109996637/231606958-278e0416-ea62-44ae-b53b-37e7f8282902.png)

**Comment by Kenneth-OPT** [comment]
> @Kenneth-OPT , je t'ai ajouté la conf qui avait resolu le pb de mon coté. Je l'ai mis sur la branche https://github.com/opt-nc/opt-temps-attente-agences-camel/tree/fix/docker_compose
> 
> Essaie le docker-compose pour voir si ca regle ton pb avant de faire le merge.

@mbarre ,

Pour info perso, c'est cette partie de la conf que tu as mis à jour ?
![image](https://user-images.githubusercontent.com/109996637/231607081-16dfae77-3148-4bd7-bda8-411fcb5fde1e.png)

**Comment by adriens** [comment]
De mon côté, j'ai viré l'entrée dans `/etc/host` afin d'avoir un env clean.

**Comment by adriens** [comment]
J'attends votre GO pour puller/tester

**Comment by Kenneth-OPT** [comment]
Malheureusement toujours le même comportement :sob:

Ci-dessous le log sans mise à jour du host et après mise à jour
![image](https://user-images.githubusercontent.com/109996637/231607681-8cba743d-705e-46ff-9c4b-f2d90a7e5a3c.png)

Et après Kowl est tout content
![image](https://user-images.githubusercontent.com/109996637/231607808-51b8440e-631d-4ca9-81dc-4b65cd01f2f6.png)

**Comment by mbarre** [comment]
>Pour info perso, c'est cette partie de la conf que tu as mis à jour ?
 
oui

**Comment by mbarre** [comment]
tu as essayé de virer tes anciens conteneurs, et repartir de zero avec le docker compose ? Est-ce que tu utilises [Portainer](https://www.portainer.io/) si oui j'aimerai bien avoir une capture d'ecran de la partie ENV du Kafka stp ?

**Comment by Kenneth-OPT** [comment]
J'avoues que j'ai eu un doute en te lisant 😅 
Oui je l'avais fait  et encore refait à l'instant, même punition.

Je ne connaissais par [Portainer](https://www.portainer.io/), merci bien pour le lien. 👍 
J'essaie de l'installer dans l'aprem.

Sinon, si demain matin tu es au bureau, je pourrai te montrer le comportement avec Docker Desktop sur le portable.

**Comment by mbarre** [comment]
> Sinon, si demain matin tu es au bureau, je pourrai te montrer le comportement avec Docker Desktop sur le portable.

yes parfait, ce sera plus simple :smile:

**Comment by adriens** [comment]
Joli joli, ça va envoyer du pâté.

@mbarre soulève un point important : tout casser régulièrement est très important.

**Comment by mbarre** [comment]
Ca y est, on a un docker-compose qui fonctionne sur mon poste 😄 
@Kenneth-OPT a toi de valider sur le tien dès que tu as récupéré de l'espace disque  😸

**Comment by Kenneth-OPT** [comment]
C'est good en Powershell avec qques ajustements
![image](https://user-images.githubusercontent.com/109996637/232934628-92387321-d0eb-49c4-b577-29ecbdb14d52.png)

Mon WSL me fait des misères (encore...), je vais voir avec @AntoineArthurG  s'il a de la dispo pour qu'on valide sur son poste Linux.

**Comment by adriens** [comment]
Ok, je tourne le test sur ma machine :crossed_fingers:

**Comment by adriens** [comment]
Ok, c'est parti : 

- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/26

**Comment by adriens** [comment]
:warning: @Kenneth-OPT  @AntoineArthurG  :point_down: 

- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/26#issuecomment-1515391992
