### ISSUE TITLE
:baby: RUN from scratch et finalisation éval :teacher: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-camel#26]
# :dart: Actions

- [ ] Faire tourner le produit en loca avec la doc
- [x] Fournir les évaluations à l'UNC

# :tickets: Issues liées

- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/24
- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/23
- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/20
- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/12
- [Evaluation Entreprise stage Info UNC.pdf](https://github.com/opt-nc/opt-temps-attente-agences-camel/files/11337134/Evaluation.Entreprise.stage.Info.UNC.pdf)

**Comment by adriens** [comment]
:stop_sign: 

- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/20#issuecomment-1505983550

Les gars, lisez et prenez en compte les feedbacks :pray: 

Protoccole de test mis en pause.

Vous testez et ensuite je ferai le test final.

**Comment by mbarre** [comment]
@Kenneth-OPT , @AntoineArthurG,

Je viens de lire vite fait les rertours d'@adrien, certains ont déjà été corrigés hier lors de mes modifs/corrections dans le QUICKSTART.md, sur la branch `fix/docker_compose` ne refaites pas tout :smile:

**Comment by adriens** [comment]
Yes, j'aimerai bien fixer cela au plus tard demain matin afin de livrer l'éval à l'UNC

**Comment by Kenneth-OPT** [comment]
> @Kenneth-OPT , @AntoineArthurG,
> 
> Je viens de lire vite fait les rertours d'@adrien, certains ont déjà été corrigés hier lors de mes modifs/corrections dans le QUICKSTART.md, sur la branch `fix/docker_compose` ne refaites pas tout 😄

Surtout pas  :sweat_smile:
Par contre on a fait d'autres changements dans le yaml.
Je t'en parlerai demain.

**Comment by Kenneth-OPT** [comment]
> Yes, j'aimerai bien fixer cela au plus tard demain matin afin de livrer l'éval à l'UNC

:+1: si tu veux on pourra le faire ensemble

Les nouvelles modifications du yaml ont nécessité des ajustements dans les routes et dans le quickstart.sh.

@AntoineArthurG  doit valider que c'est fonctionnel sur un Linux et, si tout va bien, ensuite on va pusher le code du la branche de @mbarre avant de la merger.

**Comment by adriens** [comment]
> @AntoineArthurG doit valider que c'est fonctionnel sur un Linux et, si tout va bien, ensuite on va pusher le code du la branche de @mbarre avant de la merger.

j'aime quand tu me parles comme ça 🤩

**Comment by adriens** [comment]
test de la [`v1.0`](https://github.com/opt-nc/opt-temps-attente-agences-camel/releases/tag/v1.0)

**Comment by adriens** [comment]
Evaluation en cours :hourglass:

**Comment by adriens** [comment]
Bloqué par : 

- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/27

**Comment by adriens** [comment]
:pause_button:

**Comment by adriens** [comment]
Les gars, des news ?

**Comment by adriens** [comment]
Rédaction des evals en cours...

**Comment by adriens** [comment]
Evaluations livrées
![image](https://user-images.githubusercontent.com/5235127/234708580-1b871a40-a46e-4383-87f6-9759f5fb2b1e.png)
![image](https://user-images.githubusercontent.com/5235127/234708632-c91bb256-c175-402c-bc6c-1ef4141fde24.png)
