### ISSUE TITLE
:rotating_light:  Impossible de démarrer la solution sur v1.0 :rotating_light: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-camel#27]
# :grey_question: A propos

Lors de la finalisation de l'évaluation:

- https://github.com/opt-nc/opt-temps-attente-agences-camel/issues/26

Je n'arrive pas à faire tourner la solution from scratch : 

- [ ] `Connect to ipv4#127.0.0.1:9094 failed: Connection refused`
- [ ] `./quickstart.sh: line 39: camel: command not found`

# :scroll: Logs

<pre><font color="#5FD700">❯</font> sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:41871         0.0.0.0:*               <font color="#EF2929"><b>LISTEN</b></font>      676778/nemo         
tcp        0      0 127.0.0.53:53           0.0.0.0:*               <font color="#EF2929"><b>LISTEN</b></font>      664/systemd-resolve 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               <font color="#EF2929"><b>LISTEN</b></font>      678854/cupsd        
tcp        0      0 192.168.1.27:41871      0.0.0.0:*               <font color="#EF2929"><b>LISTEN</b></font>      676778/nemo         
tcp        0      0 10.59.162.1:53          0.0.0.0:*               <font color="#EF2929"><b>LISTEN</b></font>      1434/dnsmasq        
tcp        0      0 127.0.0.1:34005         0.0.0.0:*               <font color="#EF2929"><b>LISTEN</b></font>      945/containerd      
tcp6       0      0 ::1:41871               :::*                    <font color="#EF2929"><b>LISTEN</b></font>      676778/nemo         
tcp6       0      0 ::1:631                 :::*                    <font color="#EF2929"><b>LISTEN</b></font>      678854/cupsd        
tcp6       0      0 fe80::33ee:dfef:c:41871 :::*                    <font color="#EF2929"><b>LISTEN</b></font>      676778/nemo         
<font color="#5FD700">❯</font> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
<font color="#5FD700">❯</font> ./quickstart.sh
Lancement des conteneurs
Starting optnc_api_tps_attente_kml ... <font color="#4E9A06">done</font>
Starting zookeeper_tps_attente_kml ... <font color="#4E9A06">done</font>
Starting kafka_tps_attente_kml     ... <font color="#4E9A06">done</font>
Starting red_panda_tps_attente_kml ... <font color="#4E9A06">done</font>
Vérification de l&apos;existance du topic Kafka temps-attente
%3|1682285357.634|FAIL|rdkafka#producer-1| [thrd:localhost:9094/bootstrap]: localhost:9094/bootstrap: Connect to ipv4#127.0.0.1:9094 failed: Connection refused (after 0ms in state CONNECT)
%3|1682285358.633|FAIL|rdkafka#producer-1| [thrd:localhost:9094/bootstrap]: localhost:9094/bootstrap: Connect to ipv4#127.0.0.1:9094 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
% ERROR: Failed to acquire metadata: Local: Broker transport failure
Error response from daemon: Container 82ac5caedd79b432429667807c47e9515f006be55994f4736aa4d27c5aeef01a is not running
La création du topic temps-attente a échoué.
Lancement de la route Camel API temps d&apos;attente vers Kafka
Le PID du processus Camel est : 693842
Fin du script
./quickstart.sh: line 39: camel: command not found
</pre>

**Comment by AntoineArthurG** [comment]
[Screencast from 25-04-23 17:07:44.webm](https://user-images.githubusercontent.com/71214784/234211857-b5312ba0-595c-4d8e-af68-88102b581d1d.webm)

Salut Adriens,

On a donc fait une marche à blanc sur un environnement complètement clean (donc sur la VM dont je parlais hier) et on a pas réussi à retrouver la même erreur mais une autre à la place. La petite vidéo illustre la marche à blanc et l'erreur produite. 

Par contre sur nos environnements perso on a bien réussi à reproduire ton erreur, Kenneth a proposé un fix et ça a l'air d'avoir eu un effet positif sauf sur la fréquence d'arrivée des messages. 

Je vais essayé de push le fix sur cette branche

**Comment by adriens** [comment]
Déja @AntoineArthurG , le travail ici produit, la video, le scénario de reprodction... et la collab sont un trs bon travail.
Le plus important au quotidien est de savoir investiguer, reproduire et communiquer.
Je suis extrêmement satisfait de la démarche... qui est précieuse en entreprise.

> Par contre sur nos environnements perso on a bien réussi à reproduire ton erreur, Kenneth a proposé un fix et ça a l'air d'avoir eu un effet positif sauf sur la fréquence d'arrivée des messages.
> Je vais essayé de push le fix sur cette branche

Okay, c'est good, ça avance et vous lâchez rien. Je vais faire l'éval demain matin de mon côté.

**Comment by AntoineArthurG** [comment]
Sweet merci Adriens !! Je prends bien note pour le futur et pour veiller à bien appliquer ces conseils précieux :smiley: 

Ha j'ai oublié de préciser un comportement qu'on a remarqué avec Kenneth. Lorsqu'on a lancé le quickstart.sh une première fois on est tombé sur l'erreur comme vu dans la vidéo mais en lançant le script une seconde fois, la par contre on a rencontré aucun problème et la route fonctionnait comme attendu...

Peut-être faire un test avec le yaml que Michèle avait fait aussi. Il n'avait pas marché sur nos environnements mais peut-être que la situation sera inverse de votre coté ?

**Comment by adriens** [comment]
Tu veux que je joue quoi comme script ? Donne moi le script et je joue le scénario.
No problemo :smile_cat:

**Comment by adriens** [comment]
Dis moi que quelle branche je dois taper et c parti :zap:

**Comment by AntoineArthurG** [comment]
Alors c'est la branche actuelle numéro 27 avec un nom a rallonge parce que j'ai pas fait gaffe a l'entièreté du nom. 

Du coup tu fait : 
`git fetch origin`
`git checkout 27-rotating_light-impossible-de-démarrer-la-solution-sur-v10-rotating_light`
`cd scripts/`
`./quickstart.sh`

**Comment by adriens** [comment]
No problemo pour `27-rotating_light-impossible-de-démarrer-la-solution-sur-v10-rotating_light`, a a éécréé via l'isue :+1: 

```shell
git fetch origin
git checkout 27-rotating_light-impossible-de-démarrer-la-solution-sur-v10-rotating_light
cd scripts
./quickstart.sh
```

**Comment by AntoineArthurG** [comment]
Si l'erreur suivante est toujours présente : 
./quickstart.sh: line 39: camel: command not found

Tu fait un : 
`jbang app install camel@apache/camel`

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/234252627-4dc1b2e7-bb12-42bf-a081-f338e54dbe68.png)

**Comment by adriens** [comment]
Je laisse le refresh se faire tt seul pour voir....

**Comment by adriens** [comment]
[messages.json.gz](https://github.com/opt-nc/opt-temps-attente-agences-camel/files/11321639/messages.json.gz)

**Comment by adriens** [comment]
Par-contre, un message contient tous les temps d'attente alors que la clé du message est `idAgence` : 

![image](https://user-images.githubusercontent.com/5235127/234253583-6e4999ad-faa2-4aaf-9aea-124f5f1535d5.png)

:point_right: Normalement on aurait du avoir un message par agence

**Comment by adriens** [comment]
les messages atterrisent bien en continu sur le topic : 

![image](https://user-images.githubusercontent.com/5235127/234253912-83af6523-4a95-4d32-83b7-763da32bee97.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/234254067-b6ba99be-28d2-4012-b5b0-035b863d747d.png)
![image](https://user-images.githubusercontent.com/5235127/234254121-aa7747ff-9204-4337-bc02-ca55bbe559d9.png)

**Comment by adriens** [comment]
@AntoineArthurG  @Kenneth-OPT vous voulez basculer les messages en 1 message/agence où on arrete là ?

**Comment by AntoineArthurG** [comment]
En ce qui me concerne je peut essayer de caller 2 heures demain après le travail sans faire trop de promesses. Mais a voir avec mon binome :slightly_smiling_face:  on reviens vers toi

**Comment by adriens** [comment]
> Mais a voir avec mon binome slightly_smiling_face on reviens vers toi

:100:

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/234261240-ef103eba-22b6-402a-bc0a-a87678afa2ae.png)

je lui coupe le sifflet pour ce soir

**Comment by adriens** [comment]
:pray:
