### ISSUE TITLE
:whale:  Puller l'image de l'API :window: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-camel#5]

**Comment by Kenneth-OPT** [comment]
On ne se refait pas... mon coeur de métier étant l'administration des serveurs Microsoft, j'utilise un OS Windows 10 et en plus un invite de commande Powershell :sunglasses:

Commande de récupération de l'image docker de l'API :
_`docker pull optnc/opt-temps-attente-agences-api`_

Une fois l'image récupérer commande du premier lancement du container associé à l'image avec attribution du nom `optnc` : 
_`docker run -d --name optnc -p 8080:8080 optnc/opt-temps-attente-agences-api:latest`_
:warning: au préalable il faut bien entendu vérifier que le port attribué au container est libre sur la machine physique 

![image](https://user-images.githubusercontent.com/109996637/210301294-a42060de-cf18-427f-a582-9dd39b837469.png)

Pour les prochains arrêt/démarrage, les commandes ci-dessous seront utilisées : 

![image](https://user-images.githubusercontent.com/109996637/210301943-44d94013-bba4-484a-b910-1a8a676293f9.png)

**Comment by adriens** [comment]
> On ne se refait pas... mon coeur de métier étant l'administration des serveurs Microsoft, j'utilise un OS Windows 10 et en plus un invite de commande Powershell sunglasses

mais c'est super @Kenneth-OPT  : de la diversité nait l'intelligence collective !... et puis cela montre que nos travaux sont bien portables :heavy_heart_exclamation: :muscle:

**Comment by adriens** [comment]
:bulb: , as tu essayé : 

- [`Oh My Posh`](https://ohmyposh.dev/) : je pense que tu devrais bien kiffer :sunglasses: 
- [Windows Terminal](https://github.com/microsoft/terminal)

**Comment by adriens** [comment]
> au préalable il faut bien entendu vérifier que le port attribué au container est libre sur la machine physique

:kiss: comment le faire en ligne de commande sous windows ?

**Comment by Kenneth-OPT** [comment]
> as tu essayé :
> 
> * [`Oh My Posh`](https://ohmyposh.dev/) : je pense que tu devrais bien kiffer 😎
> * [Windows Terminal](https://github.com/microsoft/terminal)

Merci bien, ça à l'air pas mal.
Je testerai sans faute.

**Comment by Kenneth-OPT** [comment]
Et merci pour les labels, apparemment je n'ai pas l'option pour les ajouter :cry:

**Comment by Kenneth-OPT** [comment]
> comment le faire en ligne de commande sous windows ?

Depuis un Dos/Shell : netstat -an

**Comment by adriens** [comment]
> Et merci pour les labels, apparemment je n'ai pas l'option pour les ajouter 

Ca devrait aller mieux maintenant.

**Comment by Kenneth-OPT** [comment]
> Depuis un Dos/Shell : netstat -an

En version PowerShell permettant de cibler le port à tester : 

1. Version complète
   ```powershell
     Test-NetConnection -ComputerName 'hostname/IPAddress'-Port 'port'
   ```
2. Version abrégée
   ```powershell
     tnc -ComputerName 'hostname/IPAddress'-Port 'port'
   ```

**Comment by adriens** [comment]
C'est bon ça :clap: je crois que tu es le premier à faire ça en Powershell à la DSI :1st_place_medal:
