### ISSUE TITLE
:people_holding_hands:  Discord :heavy_heart_exclamation: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-camel#6]
- [x] Avoir l'alias discord de @AntoineArthurG
- [x] Avoir l'alias discord de [Kenneth](https://www.linkedin.com/in/kenneth-opt-3498a5252/)
- [x] Inviter @AntoineArthurG et Kenneth sur le  discord de l'opt

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/207550505-e9047874-1a19-4bc0-ae4b-3b92e4c4b7c1.png)

**Comment by adriens** [comment]
:heavy_check_mark:  Chan créé

![image](https://user-images.githubusercontent.com/5235127/207550651-d711b6c4-b61f-4491-a3ed-173abde5014d.png)

**Comment by kwinunc** [comment]
Alias Discord
![image](https://user-images.githubusercontent.com/93364576/207560806-77d2d826-f936-41a9-a7bd-402d4a13dc67.png)

**Comment by adriens** [comment]
Invitation envoyée @kwinunc et @AntoineArthurG :rocket:

**Comment by adriens** [comment]
:point_right: Pour valider l'issue : dropper un commentaire sur le chan :pray:

**Comment by AntoineArthurG** [comment]
Hello, et voila mon alias : 
Antoine GINDRE#7856 
:+1:

**Comment by adriens** [comment]
> Alias Discord ![image](https://user-images.githubusercontent.com/93364576/207560806-77d2d826-f936-41a9-a7bd-402d4a13dc67.png)

Version texte :pray: et stp mettre un avatar :pray:

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/207698960-94071702-0f5d-4f06-9f95-2ced08bc10d9.png)
