### ISSUE TITLE
:calendar: Next réunion projet

### ISSUE THREAD

**Issue by AntoineArthurG** [opt-nc/opt-temps-attente-agences-camel#7]
Hello, 

Je suis en temps plein en entreprise a partir de demain jusqu'au 06 Janvier. En conséquence je vous propose les dates suivantes au choix pour notre prochaine réunion : 

- [x] 09/01
- [ ] 10/01
- [ ] 16/01
- [ ] 17/01
- [ ] 23/01
- [ ] 24/01

Je laisse @kwinunc  confirmer si il à les mêmes dates a disposition et comme ça @adriens tu pourra prendre tes congés :smiley:

Woohoo !! Première issue :p

**Comment by Kenneth-OPT** [comment]
Hello,
Perso je m'adapte à vos dispos.
See you soon.

**Comment by adriens** [comment]
Helo @AntoineArthurG , top ce ticket, je te donne ces éléments dans la foulée :rocket: 

@Kenneth-OPT , pour facilier la collab, je propose que tu utilises le compte @Kenneth-OPT au lieu de @kwinunc car : 

- plus facile  à tager et savoir qui est en face du compte (important pour moi qui gère bcp de comptes)
- avatar déja complet
-

**Comment by adriens** [comment]
je propose le `2023-01-09`, 13h30 :point_down: 

![image](https://user-images.githubusercontent.com/5235127/208317188-ce94b861-95f4-43ac-b0ec-ff38fd5ac2bb.png)

**Comment by adriens** [comment]
Bascule effectuée pour @Kenneth-OPT : 

![image](https://user-images.githubusercontent.com/5235127/208317288-930ff5b3-af9f-4a84-800e-6529543f5dc9.png)

**Comment by adriens** [comment]
Invitation envoyée

**Comment by Kenneth-OPT** [comment]
Thank you bien pour l'ajout du second compte.

Pour info, je vois bien le créneau dans mon calendrier, par contre je n'ai reçu aucune invitation... 
@AntoineArthurG  tu l'as reçu ?
![image](https://user-images.githubusercontent.com/109996637/208782909-4d9735dd-7164-4d75-925f-a33bd2d56cc9.png)

**Comment by adriens** [comment]
Attends je check a de suite @Kenneth-OPT ⚡

**Comment by adriens** [comment]
J'ai ça

![image](https://user-images.githubusercontent.com/5235127/208820272-85b829a8-326d-4ea6-b3e5-70e885edc355.png)

**Comment by Kenneth-OPT** [comment]
Yes parce que ce matin j'ai parcouru mon calendrier et j'y ai directement validé la réunion, mais je n'ai reçu aucun mail de notification quand tu l'avais planifié... stranger things...

**Comment by adriens** [comment]
:clap: :point_down: 

![image](https://user-images.githubusercontent.com/5235127/209014097-910a3a01-b64b-4161-a781-d11314f35162.png)

**Comment by adriens** [comment]
:point_up: Oubliez pas en amont de, pour chacun : 

- Pousser votre code dans des fichiers dédiés afin que nous puissions les utiliser lors de la démo :pray: (passer par des issues pour cela, avec le protocole issue :arrow_right: branche :arrow_right:  PR :arrow_right: merge)
